# Generated by Django 4.0 on 2021-12-18 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serviceInstance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Service instance')),
                ('firstName', models.CharField(max_length=128, verbose_name='First name')),
                ('lastName', models.CharField(max_length=128, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
