# Generated by Django 4.0 on 2021-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('postcode', models.CharField(max_length=32, verbose_name='PostCode')),
                ('date', models.DateField(verbose_name='Date')),
                ('owner', models.CharField(max_length=128, verbose_name='Name')),
                ('make', models.CharField(max_length=32, verbose_name='Make')),
                ('model', models.CharField(max_length=32, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('postcode', models.CharField(max_length=32, verbose_name='PostCode')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('employer', models.CharField(max_length=32, verbose_name='Employer')),
                ('department', models.CharField(max_length=32, verbose_name='Department')),
            ],
        ),
    ]
