# Generated by Django 4.0.1 on 2022-02-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownership',
            name='owner',
            field=models.CharField(max_length=128, verbose_name='Owner'),
        ),
    ]
