# Generated by Django 4.0.1 on 2022-01-08 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cts', models.DateTimeField(auto_now_add=True)),
                ('uts', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(editable=False, max_length=256, unique=True)),
                ('state', models.CharField(choices=[('R', 'Requested'), ('C', 'Connected'), ('D', 'Denied')], default='R', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
