# Generated by Django 4.0.1 on 2022-01-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odis', '0002_organisation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='state',
            field=models.CharField(choices=[('C', 'Connected'), ('D', 'Denied'), ('R', 'Requested'), ('S', 'Suspended')], default='R', max_length=1),
        ),
    ]
